### ISSUE TITLE
after updating v1.0.7 to v1.0.26, started seeing below error and survey won't render.

### ISSUE THREAD

**Issue by omkardusane** [surveyjs/surveyjs#1181]
This error occurs while rendering a coplex survey after I updated the library to v1.0.26, which was working in surveyjs v1.0.7 . If you have any idea on this issue, please redirect to some literature. (Note: The survey gets built dynamically so its very difficult for me to share the surveyjson. )

```
TypeError: u.getConditionRunner is not a function
    at Function.e.runConditionsForItems (survey.vue.min.js:42)
    at t.runConditionsForItems (survey.vue.min.js:42)
    at t.runItemsCondition (survey.vue.min.js:42)
    at t.filterItems (survey.vue.min.js:42)
    at Object.<anonymous> (survey.vue.min.js:42)
    at t.e.propertyValueChanged (survey.vue.min.js:7)
    at Array.n.push (survey.vue.min.js:7)
    at eval (eval at renderActivity (bet.js:1559), <anonymous>:787:65)
    at Array.forEach (<anonymous>)
    at Object.onCreatedLoader (eval at renderActivity (bet.js:1559), <anonymous>:775:51)
```

**Comment by dmitrykurmanov** [comment]
Hello, I've tried our example with conditions and Vuejs https://surveyjs.io/Examples/Library/?id=condition-kids&platform=Vue&theme=default and it looks ok. 

Do you use surveyjs editor and error occurs there?
Could you please try older versions, so we could understand wich of them is broken.

**Comment by omkardusane** [comment]
Sorry, I forgot to mention I am using Vue version. 

I temporarily fixed this issue by following patches to the survey.vue.js
```
 ItemValue.runConditionsForItems = function (items, filteredItems, runner, values, properties) {
        if (!values) {
            values = {};
        }
        var itemValue = values["item"];
        var hasChanded = false;
        for (var i = 0; i < items.length; i++) {
            var item = items[i];
            values["item"] = item.value;
            console.log(item.runConditionsForItems, item)
            var itemRunner = item.getConditionRunner();
            if (!itemRunner) {
                itemRunner = runner;
            }
            var vis = true;
            if (itemRunner) {
                vis = itemRunner.run(values, properties);
                if (vis) {
                    filteredItems.push(item);
                }
            }
            else {
                filteredItems.push(item);
            }
            if (vis != item.isVisible) {
                hasChanded = true;
                item.setIsVisible(vis);
            }
        }
        if (itemValue) {
            values["item"] = itemValue;
        }
        else {
            delete values["item"];
        }
        return hasChanded;
    };
```

to 
```
 ItemValue.runConditionsForItems = function (items, filteredItems, runner, values, properties) {
        if (!values) {
            values = {};
        }
        var itemValue = values["item"];
        var hasChanded = false;
        for (var i = 0; i < items.length; i++) {
            var item = items[i];
            values["item"] = item.value;
            console.log(item.runConditionsForItems, item)
            var itemRunner = (!!item.getConditionRunner) ?item.getConditionRunner():false;
            if (!itemRunner) {
                itemRunner = runner;
            }
            var vis = true;
            if (itemRunner) {
                vis = itemRunner.run(values, properties);
                if (vis) {
                    filteredItems.push(item);
                }
            }
            else {
                filteredItems.push(item);
            }
            if (vis != item.isVisible) {
                hasChanded = true;
                if(!!item.setIsVisible)
                    item.setIsVisible(vis);
            }
        }
        if (itemValue) {
            values["item"] = itemValue;
        }
        else {
            delete values["item"];
        }
        return hasChanded;
    };
```

**Comment by dmitrykurmanov** [comment]
@omkardusane we've added your fix to our code, thanks.

**Comment by omkardusane** [comment]
Thanks @dmitrykurmanov

**Comment by omkardusane** [comment]
@dmitrykurmanov 
Hi, 
I just pulled this fix in 1.0.32 (till now I was using the lib containing my changes) and now I am seeing this error in the console. Though it is not making any functionality broken. but still, it seems like something is wrong.

```
survey.vue.min.js:6 Uncaught TypeError: Cannot read property 'strChanged' of undefined
    at Function.e.locStrsChanged (survey.vue.min.js:6)
    at t.e.locStrsChanged (survey.vue.min.js:6)
    at t.locStrsChanged (survey.vue.min.js:6)
    at t.locStrsChanged (survey.vue.min.js:6)
    at t.locStrsChanged (survey.vue.min.js:6)
    at t.notifyElementsOnAnyValueOrVariableChanged (survey.vue.min.js:6)
    at t.notifyQuestionOnValueChanged (survey.vue.min.js:6)
    at t.setValue (survey.vue.min.js:6)
    at t.setValueCore (survey.vue.min.js:6)
    at t.setNewValueInData (survey.vue.min.js:6)

survey.vue.min.js:6 Uncaught TypeError: Cannot read property 'strChanged' of undefined
    at Function.e.locStrsChanged (survey.vue.min.js:6)
    at t.e.locStrsChanged (survey.vue.min.js:6)
    at t.locStrsChanged (survey.vue.min.js:6)
    at t.locStrsChanged (survey.vue.min.js:6)
    at t.locStrsChanged (survey.vue.min.js:6)
    at t.notifyElementsOnAnyValueOrVariableChanged (survey.vue.min.js:6)
    at t.notifyQuestionOnValueChanged (survey.vue.min.js:6)
    at t.setValue (survey.vue.min.js:6)
    at eval (eval at renderActivity (bet.js:1611), <anonymous>:964:39)
```
